# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: couchdb_exporter
    release: prometheus
    properties:
      couchdb_exporter:
        couchdb:
          uri: "((couchdb_uri))"

