---
name: prometheus

instance_groups:
  - name: alertmanager
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: alertmanager
        release: prometheus
        properties:
          alertmanager:
            mesh:
              password: ((alertmanager_mesh_password))
            route:
              receiver: default
            receivers:
              - name: default
            test_alert:
              daily: true

  - name: prometheus
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: prometheus
        release: prometheus
        properties:
          prometheus:
            rule_files:
              - /var/vcap/jobs/postgres_alerts/*.alerts
              - /var/vcap/jobs/prometheus_alerts/*.alerts
            scrape_configs:
              - job_name: prometheus
                static_configs:
                - targets:
                  - localhost:9090

  - name: grafana
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: grafana
        release: prometheus
        properties:
          grafana:
            session:
              provider: file
            security:
              admin_user: admin
              admin_password: ((grafana_password))
              secret_key: ((grafana_secret_key))
            dashboards:
              json:
                enabled: true
            prometheus:
              dashboard_files:
                - /var/vcap/jobs/grafana_dashboards/*.json
                - /var/vcap/jobs/postgres_dashboards/*.json
                - /var/vcap/jobs/prometheus_dashboards/*.json
                - /var/vcap/jobs/system_dashboards/*.json
                - /var/vcap/jobs/haproxy_dashboards/*.json
                - /var/vcap/jobs/rabbitmq_dashboards/*.json
      - name: grafana_dashboards
        release: prometheus
      - name: postgres_dashboards
        release: prometheus
      - name: prometheus_dashboards
        release: prometheus
      - name: system_dashboards
        release: prometheus
      - name: haproxy_dashboards
        release: prometheus
      - name: rabbitmq_dashboards
        release: prometheus

variables:
  - name: alertmanager_password
    type: password
  - name: alertmanager_mesh_password
    type: password
  - name: prometheus_password
    type: password
  - name: postgres_grafana_password
    type: password
  - name: grafana_password
    type: password
  - name: grafana_secret_key
    type: password

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

releases:
- name: prometheus
  version: 20.0.0
  url: https://github.com/bosh-prometheus/prometheus-boshrelease/releases/download/v20.0.0/prometheus-20.0.0.tgz
  sha1: ed8f42ab7dddc4b660a0f884748a80c2dfc470c7
